---
community_name: CPF-ApplicationTPC
community_org_url: https://gitcode.com/CPF-ApplicationTPC
community_logo_url:
resource_types:
  software-artifact-repositories:
    repo_urls:
    - https://gitcode.com/CPF-ApplicationTPC/ohos_ffmpeg
    - https://gitcode.com/CPF-ApplicationTPC/ohos_sentry
    - https://gitcode.com/CPF-ApplicationTPC/mpv
    - https://gitcode.com/CPF-ApplicationTPC/ohos_bindingx_core
    - https://gitcode.com/CPF-ApplicationTPC/SubWinWaveWheel
    - https://gitcode.com/CPF-ApplicationTPC/aws-sdk-js-v3
    - https://gitcode.com/CPF-ApplicationTPC/ohos_usb_serial
    - https://gitcode.com/CPF-ApplicationTPC/ohos_VTable
    - https://gitcode.com/CPF-ApplicationTPC/md360player
    - https://gitcode.com/CPF-ApplicationTPC/ohos_mind_elixir
    - https://gitcode.com/CPF-ApplicationTPC/photo-deal-demo
    - https://gitcode.com/CPF-ApplicationTPC/linphone_napi
    - https://gitcode.com/CPF-ApplicationTPC/oboe
    - https://gitcode.com/CPF-ApplicationTPC/ohos_fluidsynth
    - https://gitcode.com/CPF-ApplicationTPC/cicd
    - https://gitcode.com/CPF-ApplicationTPC/manifest
    - https://gitcode.com/CPF-ApplicationTPC/ohos_HtmlSpanner
    - https://gitcode.com/CPF-ApplicationTPC/ohos_ViewAnimations
    - https://gitcode.com/CPF-ApplicationTPC/docs
    - https://gitcode.com/CPF-ApplicationTPC/osgearth
    - https://gitcode.com/CPF-ApplicationTPC/ohos_onnxruntime
    - https://gitcode.com/CPF-ApplicationTPC/ohos_realm-core
    - https://gitcode.com/CPF-ApplicationTPC/ohos_logan
    - https://gitcode.com/CPF-ApplicationTPC/ohos_apng-drawable
    - https://gitcode.com/CPF-ApplicationTPC/ohos_socket.io-client-cpp
    - https://gitcode.com/CPF-ApplicationTPC/ohos_bottomsheet
    - https://gitcode.com/CPF-ApplicationTPC/ohos_CountdownView
    - https://gitcode.com/CPF-ApplicationTPC/ohos_ExpandableLayout
    - https://gitcode.com/CPF-ApplicationTPC/ohos_CircularProgressBar
    - https://gitcode.com/CPF-ApplicationTPC/skills
    - https://gitcode.com/CPF-ApplicationTPC/ohos_alertView
    - https://gitcode.com/CPF-ApplicationTPC/ohos_ambilwarna
    - https://gitcode.com/CPF-ApplicationTPC/ohos_matisse
    - https://gitcode.com/CPF-ApplicationTPC/ohos_process-button
    - https://gitcode.com/CPF-ApplicationTPC/ohos_SimpleCropView
    - https://gitcode.com/CPF-ApplicationTPC/ohos_xHook
    - https://gitcode.com/CPF-ApplicationTPC/ohos_oboe
    - https://gitcode.com/CPF-ApplicationTPC/ohos_SwipeMenuListView
    - https://gitcode.com/CPF-ApplicationTPC/ohos_ical4j
    - https://gitcode.com/CPF-ApplicationTPC/ohos_amazon-kinesis-video-streams-webrtc-sdk-js
    - https://gitcode.com/CPF-ApplicationTPC/aspect
    - https://gitcode.com/CPF-ApplicationTPC/ohos_SpinKit
    - https://gitcode.com/CPF-ApplicationTPC/ohos_StatusBarUtil
    - https://gitcode.com/CPF-ApplicationTPC/ohos_flowlayout
    - https://gitcode.com/CPF-ApplicationTPC/ohos_PagerSlidingTabStrip
    - https://gitcode.com/CPF-ApplicationTPC/ohos_sticky-headers-recyclerview
    - https://gitcode.com/CPF-ApplicationTPC/ohos_FlycoRoundView
    - https://gitcode.com/CPF-ApplicationTPC/ohos_SlidingUpPanel
    - https://gitcode.com/CPF-ApplicationTPC/ohos_material-menu
    - https://gitcode.com/CPF-ApplicationTPC/ohos_ksoap2
    - https://gitcode.com/CPF-ApplicationTPC/ohos_ShineButton
    - https://gitcode.com/CPF-ApplicationTPC/ohos_mind-elixir-core
    - https://gitcode.com/CPF-ApplicationTPC/ohos_avroc
    - https://gitcode.com/CPF-ApplicationTPC/ohos_tabulator
    - https://gitcode.com/CPF-ApplicationTPC/ohos_json2md
    - https://gitcode.com/CPF-ApplicationTPC/ohos_tus_client
    - https://gitcode.com/CPF-ApplicationTPC/ohos_vlc
    - https://gitcode.com/CPF-ApplicationTPC/ohos_aisparser
    - https://gitcode.com/CPF-ApplicationTPC/lottie_turbo
    - https://gitcode.com/CPF-ApplicationTPC/imageknifepro
    - https://gitcode.com/CPF-ApplicationTPC/ohos_ffmpeg_kit
    - https://gitcode.com/CPF-ApplicationTPC/ohos_stompjs
    - https://gitcode.com/CPF-ApplicationTPC/ohos_grpc_node
    - https://gitcode.com/CPF-ApplicationTPC/ohos_mpchart
    - https://gitcode.com/CPF-ApplicationTPC/ohos_mail_base
    - https://gitcode.com/CPF-ApplicationTPC/ohos_image_view_zoom
    - https://gitcode.com/CPF-ApplicationTPC/ohos_svg
    - https://gitcode.com/CPF-ApplicationTPC/ohos_text_layout_builder
    - https://gitcode.com/CPF-ApplicationTPC/ohos_live_event_bus
    - https://gitcode.com/CPF-ApplicationTPC/ohos_dataorm
    - https://gitcode.com/CPF-ApplicationTPC/ohos-PickerView
    - https://gitcode.com/CPF-ApplicationTPC/RoundedImageView
    - https://gitcode.com/CPF-ApplicationTPC/CircleImageView
    - https://gitcode.com/CPF-ApplicationTPC/FastBle
    - https://gitcode.com/CPF-ApplicationTPC/ohos-beacon-library
    - https://gitcode.com/CPF-ApplicationTPC/ohos-SwipeLayout
    - https://gitcode.com/CPF-ApplicationTPC/xutils_bak
    - https://gitcode.com/CPF-ApplicationTPC/ohos_material_dialogs
    - https://gitcode.com/CPF-ApplicationTPC/ohos-autofittextview
    - https://gitcode.com/CPF-ApplicationTPC/ohos_subsampling_scale_image_view
    - https://gitcode.com/CPF-ApplicationTPC/ohos_danmaku_flame_master
    - https://gitcode.com/CPF-ApplicationTPC/okdownload
    - https://gitcode.com/CPF-ApplicationTPC/WheelPicker_bak
    - https://gitcode.com/CPF-ApplicationTPC/ohos_logback
    - https://gitcode.com/CPF-ApplicationTPC/MultiType
    - https://gitcode.com/CPF-ApplicationTPC/juniversalchardet
    - https://gitcode.com/CPF-ApplicationTPC/ohos_material_progress_bar
    - https://gitcode.com/CPF-ApplicationTPC/recyclerview-animators
    - https://gitcode.com/CPF-ApplicationTPC/ohos_circle_indicator
    - https://gitcode.com/CPF-ApplicationTPC/mp3agic
    - https://gitcode.com/CPF-ApplicationTPC/jchardet
    - https://gitcode.com/CPF-ApplicationTPC/is-png
    - https://gitcode.com/CPF-ApplicationTPC/ohos_checksum
    - https://gitcode.com/CPF-ApplicationTPC/is-webp
    - https://gitcode.com/CPF-ApplicationTPC/Hamcrest
    - https://gitcode.com/CPF-ApplicationTPC/ohos_crypto_js
    - https://gitcode.com/CPF-ApplicationTPC/jama
    - https://gitcode.com/CPF-ApplicationTPC/ohos_jmustache
    - https://gitcode.com/CPF-ApplicationTPC/snakeyaml_bak
    - https://gitcode.com/CPF-ApplicationTPC/qr-code-generator
    - https://gitcode.com/CPF-ApplicationTPC/mars
    - https://gitcode.com/CPF-ApplicationTPC/ohos_base64
    - https://gitcode.com/CPF-ApplicationTPC/avro
    - https://gitcode.com/CPF-ApplicationTPC/jsoup
    - https://gitcode.com/CPF-ApplicationTPC/commons-cli
    - https://gitcode.com/CPF-ApplicationTPC/brotli
    - https://gitcode.com/CPF-ApplicationTPC/jtar
    - https://gitcode.com/CPF-ApplicationTPC/dd-plist
    - https://gitcode.com/CPF-ApplicationTPC/ohos_vlayout
    - https://gitcode.com/CPF-ApplicationTPC/shimmer-ohos
    - https://gitcode.com/CPF-ApplicationTPC/RecyclerViewPager
    - https://gitcode.com/CPF-ApplicationTPC/overscroll-decor
    - https://gitcode.com/CPF-ApplicationTPC/ohos_apng
    - https://gitcode.com/CPF-ApplicationTPC/ohos_ijkplayer
    - https://gitcode.com/CPF-ApplicationTPC/aki
    - https://gitcode.com/CPF-ApplicationTPC/ohos_jsonwebtoken
    - https://gitcode.com/CPF-ApplicationTPC/ohos_banner
    - https://gitcode.com/CPF-ApplicationTPC/ohos_videocompressor
    - https://gitcode.com/CPF-ApplicationTPC/ohos_highlightguide
    - https://gitcode.com/CPF-ApplicationTPC/ohos_video_trimmer
    - https://gitcode.com/CPF-ApplicationTPC/tpc_resource
    - https://gitcode.com/CPF-ApplicationTPC/openharmony_tpc_samples
    - https://gitcode.com/CPF-ApplicationTPC/ohos_polyfill
    - https://gitcode.com/CPF-ApplicationTPC/ohos_axios
    - https://gitcode.com/CPF-ApplicationTPC/tpc_c_cplusplus
    - https://gitcode.com/CPF-ApplicationTPC/ohos_disklrucache
    - https://gitcode.com/CPF-ApplicationTPC/ohos_gif-drawable
    - https://gitcode.com/CPF-ApplicationTPC/ohos_commons-fileupload
    - https://gitcode.com/CPF-ApplicationTPC/ohos_pull_to_refresh
    - https://gitcode.com/CPF-ApplicationTPC/ohos_fileio-extra
    - https://gitcode.com/CPF-ApplicationTPC/ohos_mbassador
    - https://gitcode.com/CPF-ApplicationTPC/arangojs
    - https://gitcode.com/CPF-ApplicationTPC/ohos_webrtc
    - https://gitcode.com/CPF-ApplicationTPC/VCard
    - https://gitcode.com/CPF-ApplicationTPC/CommonsCompress
    - https://gitcode.com/CPF-ApplicationTPC/arouter-api-onActivityResult
    - https://gitcode.com/CPF-ApplicationTPC/ohos_sdl2
    - https://gitcode.com/CPF-ApplicationTPC/MMKV
    - https://gitcode.com/CPF-ApplicationTPC/ohos_libpag
    - https://gitcode.com/CPF-ApplicationTPC/flexsearch-ohos
    - https://gitcode.com/CPF-ApplicationTPC/mixpanel-ohos
    - https://gitcode.com/CPF-ApplicationTPC/rebound
    - https://gitcode.com/CPF-ApplicationTPC/thrift
    - https://gitcode.com/CPF-ApplicationTPC/LargeImage
    - https://gitcode.com/CPF-ApplicationTPC/XmlGraphicsBatik
    - https://gitcode.com/CPF-ApplicationTPC/lottieArkTS
    - https://gitcode.com/CPF-ApplicationTPC/commons-codec
    - https://gitcode.com/CPF-ApplicationTPC/mp4parser
    - https://gitcode.com/CPF-ApplicationTPC/zxing
    - https://gitcode.com/CPF-ApplicationTPC/httpclient
    - https://gitcode.com/CPF-ApplicationTPC/okio
    - https://gitcode.com/CPF-ApplicationTPC/retrofit
    - https://gitcode.com/CPF-ApplicationTPC/RocketChat
    - https://gitcode.com/CPF-ApplicationTPC/ImageKnife
    - https://gitcode.com/CPF-ApplicationTPC/commonmark
    - https://gitcode.com/CPF-ApplicationTPC/protobuf
    - https://gitcode.com/CPF-ApplicationTPC/pdfViewer
    - https://gitcode.com/CPF-ApplicationTPC/opencsv
    - https://gitcode.com/CPF-ApplicationTPC/pinyin4js
    - https://gitcode.com/CPF-ApplicationTPC/node-csv
    - https://gitcode.com/CPF-ApplicationTPC/ohos_mqtt
    - https://gitcode.com/CPF-ApplicationTPC/ohos_mail
    - https://gitcode.com/CPF-ApplicationTPC/ohos_coap
    - https://gitcode.com/CPF-ApplicationTPC/ohos_ftp_srv
  governance-repositories:
    repo_urls: []
